version: 2

sources:
  - name: source
    database: dbtproject  
    schema: source  
    tables:
      - name: fact_sales
      - name: fact_returns
      - name: dim_product
      - name: dim_customer
      - name: dim_store
      - name: dim_date


